### ISSUE TITLE
 fatal error: gsl/gsl_bst.h

### ISSUE THREAD

**Issue by beiqinyouxian** [ImperialCollegeLondon/EventEMin#4]
avl.c:29:10: fatal error: gsl/gsl_bst.h: 没有那个文件或目录
   29 | #include <gsl/gsl_bst.h>
      |          ^~~~~~~~~~~~~~~
compilation terminated.

**Comment by umgnunes** [comment]
Hi!

You'll have to give more info regarding your issue. From what you've shared, the issue seems to be related with compiling [gsl](https://www.gnu.org/software/gsl/).

**Comment by umgnunes** [comment]
Closed due to inactivity. Please feel free to open it again if any issue arises. Thanks.
