### ISSUE TITLE
how to add an additional column to the event.txt

### ISSUE THREAD

**Issue by JianxiangL** [ImperialCollegeLondon/EventEMin#6]
hi!
thank you for your excellent code!
I want to run your 6dof code with another dataset, but how can I add an additional column corresponding to the depth of each event to every row in the event.txt file?

**Comment by umgnunes** [comment]
Hi, thanks for your interest!

There are several ways, but the simplest is if you have the frame-based depth measures, you assign the depth of the corresponding pixel and time (more or less). That was the way the [example sequence](https://github.com/ImperialCollegeLondon/EventEMin/tree/master/dataset/indoor_flying1) was generated.
